List<String> focusList = [
  "Praise God for Who He Is",
  "Thank God for What He Has Done",
  "Remember God’s Love and Grace for You",
  "Pray That You Would Love Your Neighbors",
  "Talk to God About Someone in Need",
  "Pray for Someone Who Does Not Yet Know Jesus",
  "Pray That You Would Love Your Enemies",
  "Pray That You Would Give Your Time, Money and Energy",
  "Pray for Your Church or Christian Community",
  "Pray for Your City, Nation and Civic Leaders",
  "Pray for Kindness",
  "Pray for Humility",
  "Pray for The Ability to Forgive",
  "Pray for Obedience",
  "Pray for Your Mind to Be Renewed",
  "Pray for Purity",
  "Pray for Responsibility",
  "Pray for Hope",
  "Pray for Courage",
  "Pray for Israel",
  "Pray for Revival",
  "Pray for Peace",
  "Pray for Wisdom",
];
